In [1]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\t.t_s\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\t.t_s\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\t.t_s\anaconda3\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\t.t_s\anaconda3\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\t.t_s\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\t.t_s\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t.t_s\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\t.t_s\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import seaborn as sns
df= sns.load_dataset('titanic')

In [24]:
print(df.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third
1         1       1  female  38.0      1      0  71.2833        C   First
2         1       3  female  26.0      0      0   7.9250        S   Third
3         1       1  female  35.0      1      0  53.1000        S   First
4         0       3    male  35.0      0      0   8.0500        S   Third
5         0       3    male   NaN      0      0   8.4583        Q   Third
6         0       1    male  54.0      0      0  51.8625        S   First
7         0       3    male   2.0      3      1  21.0750        S   Third
8         1       3  female  27.0      0      2  11.1333        S   Third
9         1       2  female  14.0      1      0  30.0708        C  Second

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
5    man        True  NaN   Queenstown    no   True
6    man        True    E  Southampton    no   True
7  child       False  NaN  Southampton    no  False
8  woman       False  NaN  Southampton   yes  False
9  child       False  NaN    Cherbourg   yes  False

In [25]:
#lazimsiz ve tekrarlana sutunlari  sil
df_clean=df.drop(['alive','class','who','deck','embark_town'],axis=1)

In [26]:
#age sutunu bosluqlari doldur
df_clean['age']=df_clean['age'].fillna(df_clean['age'].mean())

# 'embarked' sütununda ən çox təkrar olunan limanı tapaq (Mode)
most_common_port = df_clean['embarked'].mode()[0]
print(f"Ən çox istifadə olunan liman: {most_common_port}")
df_clean['embarked'] = df_clean['embarked'].fillna(most_common_port)

Ən çox istifadə olunan liman: S

In [27]:
print(df_clean.isnull().sum())
print('yeni cedvelin ilk sutunlari',df_clean.head())

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
adult_male    0
alone         0
dtype: int64
yeni cedvelin ilk sutunlari    survived  pclass     sex   age  sibsp  parch     fare embarked  adult_male  \
0         0       3    male  22.0      1      0   7.2500        S        True
1         1       1  female  38.0      1      0  71.2833        C       False
2         1       3  female  26.0      0      0   7.9250        S       False
3         1       1  female  35.0      1      0  53.1000        S       False
4         0       3    male  35.0      0      0   8.0500        S        True

   alone
0  False
1  False
2   True
3  False
4   True

In [28]:
df_clean['embarked']=df_clean['embarked'].map({'S':0,'C':1,'Q':2})
df_clean.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,3,male,22.0,1,0,7.2500,0,True,False
1,1,1,female,38.0,1,0,71.2833,1,False,False
2,1,3,female,26.0,0,0,7.9250,0,False,True
3,1,1,female,35.0,1,0,53.1000,0,False,False
4,0,3,male,35.0,0,0,8.0500,0,True,True

In [29]:
df_clean['sex']=df_clean['sex'].map({'male':1,'female':0})
df_clean

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,3,1,22.000000,1,0,7.2500,0,True,False
1,1,1,0,38.000000,1,0,71.2833,1,False,False
2,1,3,0,26.000000,0,0,7.9250,0,False,True
3,1,1,0,35.000000,1,0,53.1000,0,False,False
4,0,3,1,35.000000,0,0,8.0500,0,True,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,0,True,True
887,1,1,0,19.000000,0,0,30.0000,0,False,True
888,0,3,0,29.699118,1,2,23.4500,0,False,False
889,1,1,1,26.000000,0,0,30.0000,1,True,True
890,0,3,1,32.000000,0,0,7.7500,2,True,True

In [34]:
#Model qururuq
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
X=df_clean.drop('survived',axis=1)
y=df_clean['survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Modelin dəqiqliyi: {accuracy * 100:.2f}%")

Modelin dəqiqliyi: 82.68%